/*
  قيد العقار — ثوابت التطبيق (مستخرجة من App.jsx)
  الخطوة 1: استخراج الثوابت والدوال المساعدة
*/

// ============================================
// STORAGE_KEYS — مفاتيح localStorage الموحّدة (SPR-003: نُقلت من assets/js/core/keys.js)
// ============================================
export const STORAGE_KEYS = {
  // Financial
  TRANSACTIONS: 'ff_transactions',
  COMMISSIONS: 'ff_commissions',
  DRAFTS: 'ff_drafts',
  SETTINGS: 'ff_settings',
  SEEDED: 'ff_seeded',
  // Real estate — SPR-018
  PROPERTIES: 'ff_properties',
  UNITS: 'ff_units',
  CONTACTS: 'ff_contacts',
  CONTRACTS: 'ff_contracts_v1',
  CONTRACT_PAYMENTS: 'ff_contract_payments_v1',
  CONTRACT_RECEIPTS: 'ff_contract_receipts_v1',
  // UI
  UI_THEME: 'ui_theme',
  UI_NUMERALS: 'ui_numerals',
  UI_DATE_HEADER: 'ui_date_header',
  UI_ONBOARDING: 'ui_onboarding_seen',
  UI_WELCOME: 'hasSeenWelcomeBanner',
  UI_TOUR: 'ui_tour_seen',
  OFFICE_LOGO: 'ff_office_logo',
};

// ============================================
// KEYS (اختصار — متوافق مع dataStore.js)
// ============================================
export const KEYS = {
  transactions: STORAGE_KEYS.TRANSACTIONS,
  commissions: STORAGE_KEYS.COMMISSIONS,
  drafts: STORAGE_KEYS.DRAFTS,
  settings: STORAGE_KEYS.SETTINGS,
  seeded: STORAGE_KEYS.SEEDED,
  properties: STORAGE_KEYS.PROPERTIES,
  units: STORAGE_KEYS.UNITS,
  contacts: STORAGE_KEYS.CONTACTS,
  contracts: STORAGE_KEYS.CONTRACTS,
  contractPayments: STORAGE_KEYS.CONTRACT_PAYMENTS,
  contractReceipts: STORAGE_KEYS.CONTRACT_RECEIPTS,
};

// ============================================
// TYPES (أنواع الحركات والعمولات والخطابات)
// ============================================
export const TRANSACTION_TYPES = { income: 'دخل', expense: 'خرج' };
export const TRANSACTION_CATEGORIES = {
  commission: 'عمولة',
  expense: 'مصروفات',
  deposit: 'إيداع',
  refund: 'استرجاع',
  salary: 'راتب',
  rent: 'إيجار',
  other: 'أخرى',
};
export const PAYMENT_METHODS = {
  cash: 'نقدي',
  bank_transfer: 'تحويل بنكي',
  check: 'شيك',
  electronic: 'بطاقة إلكترونية',
};
export const COMMISSION_STATUSES = { pending: 'معلقة', paid: 'مدفوعة' };
export const LETTER_TYPES = {
  intro: 'خطاب تعريف',
  request: 'خطاب مخاطبة',
  delegation: 'خطاب تفويض',
};

// ============================================
// العقارات — SPR-018
// ============================================
export const PROPERTY_TYPES = {
  apartment: 'شقة',
  villa: 'فيلا',
  building: 'عمارة',
  office: 'مكتب',
  chalet: 'شاليه',
  land: 'أرض',
  warehouse: 'مستودع',
  other: 'أخرى',
};

export const PROPERTY_STATUSES = {
  available: 'متاح',
  rented: 'مؤجر',
  maintenance: 'صيانة',
  sold: 'مباع',
};

export const UNIT_TYPES = {
  apartment: 'شقة',
  shop: 'محل',
  office: 'مكتب',
  studio: 'استوديو',
  room: 'غرفة',
  other: 'أخرى',
};

export const UNIT_STATUSES = {
  vacant: 'شاغرة',
  occupied: 'مؤجرة',
  maintenance: 'صيانة',
};

// ============================================
// جهات الاتصال — SPR-018
// ============================================
export const CONTACT_TYPES = {
  tenant: 'مستأجر',
  owner: 'مالك',
  buyer: 'مشتري',
  agent: 'وسيط',
  supplier: 'مورد',
  other: 'أخرى',
};

export const CONTACT_ID_TYPES = {
  national_id: 'هوية وطنية',
  iqama: 'إقامة',
  commercial_reg: 'سجل تجاري',
  passport: 'جواز سفر',
};

// ============================================
// العقود — SPR-018
// ============================================
export const CONTRACT_TYPES = {
  rent: 'إيجار',
  sale: 'بيع',
  management: 'إدارة',
  other: 'أخرى',
};

export const CONTRACT_STATUSES = {
  draft: 'مسودة',
  active: 'ساري',
  expired: 'منتهي',
  terminated: 'ملغي',
  renewed: 'مُجدد',
};

export const PAYMENT_CYCLES = {
  monthly: 'شهري',
  quarterly: 'ربع سنوي',
  semi_annual: 'نصف سنوي',
  annual: 'سنوي',
  one_time: 'دفعة واحدة',
  custom: 'مخصص',
};

// ============================================
// رسائل النجاح والخطأ والأزرار
// ============================================
export const MSG = {
  success: {
    saved: 'تم التسجيل بنجاح',
    updated: 'تم تحديث البيانات',
    deleted: 'تم الحذف بنجاح',
    transaction: 'تم تسجيل العملية المالية',
    commission: 'تم تسجيل العمولة بنجاح',
  },
  error: {
    required: 'هذا الحقل مطلوب',
    invalidAmount: 'المبلغ المدخل غير صحيح',
    duplicate: 'هذا العنصر موجود بالفعل',
    deleteFailed: 'لم يتم الحذف. يُنصح بالمحاولة مرة أخرى',
  },
  confirm: { deleteAction: 'هل أنت متأكد من هذا الإجراء؟' },
  buttons: { save: 'تسجيل البيانات', cancel: 'تراجع', delete: 'حذف نهائي' },
};

// ============================================
// خيارات فترة لوحة التحكم
// ============================================
export const DASHBOARD_PERIOD_OPTIONS = [
  { v: 'thisMonth', l: 'هذا الشهر' },
  { v: 'last3', l: 'آخر 3 أشهر' },
  { v: 'last6', l: 'آخر 6 أشهر' },
  { v: 'thisYear', l: 'هذا العام' },
  { v: 'custom', l: 'مخصص' },
];

// ============================================
// التنقل — النبض المالي (5 عناصر)
// ============================================
export const NAV_ITEMS = [
  { id: 'pulse', label: 'النبض المالي', iconKey: 'pulse' },
  { id: 'inbox', label: 'المستحقات', iconKey: 'inbox' },
  { id: 'ledgers', label: 'الدفاتر', iconKey: 'ledgers' },
  { id: 'transactions', label: 'الحركات', iconKey: 'transactions' },
  { id: 'settings', label: 'الإعدادات', iconKey: 'settings' },
];

// ============================================
// بيانات البذور (Seed) — واقعية وتغطي آخر 6 أشهر للوحة التحكم والبحث
// ============================================
export const SEED_TRANSACTIONS = [
  // أيلول 2025
  {
    type: 'income',
    category: 'commission',
    amount: 22000,
    paymentMethod: 'bank_transfer',
    date: '2025-09-05',
    description: 'عمولة بيع شقة - عميل عبدالرحمن الشمري',
  },
  {
    type: 'expense',
    category: 'rent',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2025-09-01',
    description: 'إيجار مكتب شهر سبتمبر',
  },
  {
    type: 'income',
    category: 'deposit',
    amount: 45000,
    paymentMethod: 'bank_transfer',
    date: '2025-09-12',
    description: 'دفعة عقد بيع أرض - شركة المستقبل العقارية',
  },
  {
    type: 'expense',
    category: 'expense',
    amount: 2800,
    paymentMethod: 'cash',
    date: '2025-09-18',
    description: 'صيانة دورات مياه وإصلاح إضاءة',
  },
  {
    type: 'income',
    category: 'commission',
    amount: 9500,
    paymentMethod: 'check',
    date: '2025-09-22',
    description: 'عمولة تأجير محل - حي النخيل',
  },
  {
    type: 'expense',
    category: 'salary',
    amount: 7500,
    paymentMethod: 'bank_transfer',
    date: '2025-09-28',
    description: 'راتب سكرتير مكتب',
  },
  // تشرين الأول 2025
  {
    type: 'income',
    category: 'commission',
    amount: 18500,
    paymentMethod: 'bank_transfer',
    date: '2025-10-03',
    description: 'عمولة بيع فيلا - عائلة الدوسري',
  },
  {
    type: 'expense',
    category: 'rent',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2025-10-01',
    description: 'إيجار مكتب شهر أكتوبر',
  },
  {
    type: 'income',
    category: 'refund',
    amount: 1500,
    paymentMethod: 'cash',
    date: '2025-10-08',
    description: 'استرجاع مصروف إعلان ملغى',
  },
  {
    type: 'expense',
    category: 'expense',
    amount: 4200,
    paymentMethod: 'electronic',
    date: '2025-10-15',
    description: 'إعلانات ورقية ولوحات إرشادية',
  },
  {
    type: 'income',
    category: 'commission',
    amount: 31000,
    paymentMethod: 'bank_transfer',
    date: '2025-10-20',
    description: 'عمولة بيع أرض سكنية - عميل ناصر العتيبي',
  },
  {
    type: 'expense',
    category: 'other',
    amount: 1100,
    paymentMethod: 'cash',
    date: '2025-10-25',
    description: 'مصروفات مكتبية وقرطاسية',
  },
  // تشرين الثاني 2025
  {
    type: 'income',
    category: 'commission',
    amount: 14200,
    paymentMethod: 'bank_transfer',
    date: '2025-11-02',
    description: 'عمولة تأجير فيلا - عميل خالد المطيري',
  },
  {
    type: 'expense',
    category: 'rent',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2025-11-01',
    description: 'إيجار مكتب شهر نوفمبر',
  },
  {
    type: 'income',
    category: 'deposit',
    amount: 28000,
    paymentMethod: 'check',
    date: '2025-11-10',
    description: 'دفعة عميل - صفقة بيع محل تجاري',
  },
  {
    type: 'expense',
    category: 'salary',
    amount: 7500,
    paymentMethod: 'bank_transfer',
    date: '2025-11-28',
    description: 'راتب سكرتير مكتب',
  },
  {
    type: 'income',
    category: 'commission',
    amount: 8800,
    paymentMethod: 'cash',
    date: '2025-11-15',
    description: 'عمولة وساطة تأجير شقة - حي الروضة',
  },
  {
    type: 'expense',
    category: 'expense',
    amount: 3500,
    paymentMethod: 'electronic',
    date: '2025-11-20',
    description: 'مصروفات تسويق رقمي ومنصات عقارية',
  },
  // كانون الأول 2025
  {
    type: 'income',
    category: 'commission',
    amount: 26500,
    paymentMethod: 'bank_transfer',
    date: '2025-12-05',
    description: 'عمولة بيع عمارة - شركة الأمان للاستثمار',
  },
  {
    type: 'expense',
    category: 'rent',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2025-12-01',
    description: 'إيجار مكتب شهر ديسمبر',
  },
  {
    type: 'income',
    category: 'commission',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2025-12-12',
    description: 'عمولة تأجير مكتب - شركة التقنية المتقدمة',
  },
  {
    type: 'expense',
    category: 'expense',
    amount: 2100,
    paymentMethod: 'cash',
    date: '2025-12-18',
    description: 'صيانة تكييف وتنظيف واجهة',
  },
  {
    type: 'income',
    category: 'refund',
    amount: 800,
    paymentMethod: 'cash',
    date: '2025-12-22',
    description: 'استرجاع رسوم إضافية عميل',
  },
  {
    type: 'expense',
    category: 'other',
    amount: 900,
    paymentMethod: 'cash',
    date: '2025-12-28',
    description: 'ضيافة عملاء وقهوة مكتب',
  },
  // كانون الثاني 2026
  {
    type: 'income',
    category: 'commission',
    amount: 38000,
    paymentMethod: 'bank_transfer',
    date: '2026-01-08',
    description: 'عمولة بيع أرض تجارية - عميل فيصل القحطاني',
  },
  {
    type: 'expense',
    category: 'rent',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2026-01-01',
    description: 'إيجار مكتب شهر يناير',
  },
  {
    type: 'income',
    category: 'deposit',
    amount: 52000,
    paymentMethod: 'bank_transfer',
    date: '2026-01-14',
    description: 'دفعة عقد بيع فيلا - عائلة السعيد',
  },
  {
    type: 'expense',
    category: 'salary',
    amount: 8000,
    paymentMethod: 'bank_transfer',
    date: '2026-01-30',
    description: 'راتب موظف محاسبة',
  },
  {
    type: 'income',
    category: 'commission',
    amount: 15500,
    paymentMethod: 'check',
    date: '2026-01-20',
    description: 'عمولة تأجير شقة - حي الورود',
  },
  {
    type: 'expense',
    category: 'expense',
    amount: 4100,
    paymentMethod: 'electronic',
    date: '2026-01-25',
    description: 'إعلانات وإعلانات منزلية',
  },
  // شباط 2026
  {
    type: 'income',
    category: 'commission',
    amount: 28400,
    paymentMethod: 'bank_transfer',
    date: '2026-02-03',
    description: 'عمولة بيع أرض - شركة النخيل العقارية',
  },
  {
    type: 'expense',
    category: 'rent',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    date: '2026-02-01',
    description: 'إيجار مكتب شهر فبراير',
  },
  {
    type: 'income',
    category: 'commission',
    amount: 19200,
    paymentMethod: 'bank_transfer',
    date: '2026-02-10',
    description: 'عمولة بيع محل - عميل سعد الدوسري',
  },
  {
    type: 'expense',
    category: 'expense',
    amount: 3200,
    paymentMethod: 'cash',
    date: '2026-02-07',
    description: 'مصروفات تسويق وطباعة بروشورات',
  },
  {
    type: 'income',
    category: 'refund',
    amount: 1200,
    paymentMethod: 'cash',
    date: '2026-02-12',
    description: 'استرجاع مصروفات عميل',
  },
  {
    type: 'expense',
    category: 'other',
    amount: 1850,
    paymentMethod: 'electronic',
    date: '2026-02-15',
    description: 'مصروفات متنوعة واشتراكات',
  },
];

export const SEED_COMMISSIONS = [
  {
    clientName: 'صفقة بيع فيلا - عميل خالد الشمري',
    dealValue: 850000,
    officePercent: 3,
    agentName: 'محمد السعيد',
    agentPercent: 97,
    status: 'pending',
    dueDate: '2026-03-05',
  },
  {
    clientName: 'تأجير محل تجاري - شركة النور للتجارة',
    dealValue: 320000,
    officePercent: 2,
    agentName: 'فهد العتيبي',
    agentPercent: 98,
    status: 'paid',
    dueDate: '2025-10-15',
    paidDate: '2025-10-18',
  },
  {
    clientName: 'بيع أرض سكنية - حي الملقا',
    dealValue: 650000,
    officePercent: 2.5,
    agentName: 'سارة القحطاني',
    agentPercent: 97.5,
    status: 'pending',
    dueDate: '2026-03-20',
  },
  {
    clientName: 'تأجير فيلا - عائلة الأحمد',
    dealValue: 180000,
    officePercent: 3,
    agentName: 'عبدالله المطيري',
    agentPercent: 97,
    status: 'paid',
    dueDate: '2025-09-20',
    paidDate: '2025-09-22',
  },
  {
    clientName: 'بيع شقة - عميل ناصر الدوسري',
    dealValue: 420000,
    officePercent: 2,
    agentName: 'نورة الدوسري',
    agentPercent: 98,
    status: 'pending',
    dueDate: '2026-04-01',
  },
  {
    clientName: 'استثمار عقاري - شركة الخليج للاستثمار',
    dealValue: 1500000,
    officePercent: 1.5,
    agentName: 'أحمد الشمري',
    agentPercent: 98.5,
    status: 'paid',
    dueDate: '2026-01-10',
    paidDate: '2026-01-12',
  },
  {
    clientName: 'تأجير مكتب - شركة التقنية المتقدمة',
    dealValue: 240000,
    officePercent: 2.5,
    agentName: 'ريم العتيبي',
    agentPercent: 97.5,
    status: 'paid',
    dueDate: '2025-12-01',
    paidDate: '2025-12-03',
  },
  {
    clientName: 'بيع أرض تجارية - عميل فيصل القحطاني',
    dealValue: 1200000,
    officePercent: 2,
    agentName: 'خالد المطيري',
    agentPercent: 98,
    status: 'pending',
    dueDate: '2026-04-15',
  },
  {
    clientName: 'تأجير شقة - عميل عبدالرحمن',
    dealValue: 90000,
    officePercent: 3,
    agentName: 'لطيفة السعيد',
    agentPercent: 97,
    status: 'paid',
    dueDate: '2025-11-10',
    paidDate: '2025-11-12',
  },
  {
    clientName: 'بيع محل - حي النخيل',
    dealValue: 580000,
    officePercent: 2.5,
    agentName: 'سعد الدوسري',
    agentPercent: 97.5,
    status: 'pending',
    dueDate: '2026-03-25',
  },
];

export const SEED_DRAFTS = [
  {
    templateType: 'intro',
    fields: {
      officeName: 'مكتب مثال العقاري',
      recipientName: 'السيد أحمد',
      recipientOrg: 'شركة العقار الذهبي',
      date: '2025-02-15',
      managerName: 'خالد الأحمد',
    },
  },
  {
    templateType: 'request',
    fields: {
      officeName: 'مكتب مثال العقاري',
      recipientOrg: 'بلدية بريدة',
      subject: 'طلب تصريح',
      body: 'نرجو التكرم بإصدار تصريح...',
      date: '2025-02-10',
      managerName: 'خالد الأحمد',
    },
  },
];

export const SEED_SETTINGS = {
  officeName: 'مكتب مثال العقاري',
  phone: '0501234567',
  email: 'info@example-realestate.sa',
  defaultCommissionPercent: 50,
  theme: 'light',
  numerals: 'ar',
};

export const SEED_CONTACTS = [
  {
    id: 'contact-owner-001',
    name: 'خالد بن سعد العتيبي',
    type: 'owner',
    phone: '0551203344',
    phone2: '',
    email: 'k.alotaibi@example.sa',
    idNumber: '1029384756',
    idType: 'national_id',
    city: 'الرياض',
    district: 'النرجس',
    address: 'حي النرجس، طريق عثمان بن عفان',
    companyName: '',
    nationality: 'سعودي',
    tags: 'مالك,VIP',
    notes: 'مالك لعدد من الأصول السكنية والتجارية.',
    createdAt: '2026-01-03T09:15:00.000Z',
    updatedAt: '2026-01-03T09:15:00.000Z',
  },
  {
    id: 'contact-owner-002',
    name: 'نورة عبدالله القحطاني',
    type: 'owner',
    phone: '0556647788',
    phone2: '',
    email: 'n.alqahtani@example.sa',
    idNumber: '1067348291',
    idType: 'national_id',
    city: 'الرياض',
    district: 'الياسمين',
    address: 'حي الياسمين، طريق أنس بن مالك',
    companyName: '',
    nationality: 'سعودية',
    tags: 'مالك',
    notes: 'تفضّل التواصل بعد العصر.',
    createdAt: '2026-01-05T10:20:00.000Z',
    updatedAt: '2026-01-05T10:20:00.000Z',
  },
  {
    id: 'contact-tenant-001',
    name: 'عبدالله محمد الشهري',
    type: 'tenant',
    phone: '0558899100',
    phone2: '',
    email: 'a.alshahri@example.sa',
    idNumber: '1092837465',
    idType: 'national_id',
    city: 'الرياض',
    district: 'النرجس',
    address: 'شقة 101، عمارة النرجس',
    companyName: '',
    nationality: 'سعودي',
    tags: 'سكني',
    notes: 'منتظم بالسداد.',
    createdAt: '2026-01-12T08:40:00.000Z',
    updatedAt: '2026-01-12T08:40:00.000Z',
  },
  {
    id: 'contact-tenant-002',
    name: 'فيصل ناصر الدوسري',
    type: 'tenant',
    phone: '0557744112',
    phone2: '',
    email: 'f.aldosari@example.sa',
    idNumber: '2093847561',
    idType: 'iqama',
    city: 'الرياض',
    district: 'النرجس',
    address: 'شقة 102، عمارة النرجس',
    companyName: '',
    nationality: 'سعودي',
    tags: 'سكني',
    notes: '',
    createdAt: '2026-01-14T11:10:00.000Z',
    updatedAt: '2026-01-14T11:10:00.000Z',
  },
  {
    id: 'contact-tenant-003',
    name: 'مؤسسة ركن التقنية',
    type: 'tenant',
    phone: '0553412200',
    phone2: '0114982200',
    email: 'leasing@rokntech.sa',
    idNumber: '1010998877',
    idType: 'commercial_reg',
    city: 'الرياض',
    district: 'النرجس',
    address: 'محل A، عمارة النرجس',
    companyName: 'مؤسسة ركن التقنية',
    nationality: 'سعودية',
    tags: 'تجاري',
    notes: 'عقد تجاري سنوي.',
    createdAt: '2026-01-15T09:05:00.000Z',
    updatedAt: '2026-01-15T09:05:00.000Z',
  },
  {
    id: 'contact-buyer-001',
    name: 'شركة أفق التطوير العقارية',
    type: 'buyer',
    phone: '0114027766',
    phone2: '0550046677',
    email: 'acquisitions@ofoqdev.sa',
    idNumber: '1010885544',
    idType: 'commercial_reg',
    city: 'الرياض',
    district: 'القيروان',
    address: 'طريق الملك فهد',
    companyName: 'شركة أفق التطوير العقارية',
    nationality: 'سعودية',
    tags: 'مشتري,استثماري',
    notes: 'مهتم بالأراضي التجارية شمال الرياض.',
    createdAt: '2026-01-18T12:00:00.000Z',
    updatedAt: '2026-01-18T12:00:00.000Z',
  },
  {
    id: 'contact-supplier-001',
    name: 'مؤسسة روافد الصيانة',
    type: 'supplier',
    phone: '0559922114',
    phone2: '',
    email: 'ops@rawafed-maint.sa',
    idNumber: '1010332211',
    idType: 'commercial_reg',
    city: 'الرياض',
    district: 'العليا',
    address: 'حي العليا',
    companyName: 'مؤسسة روافد الصيانة',
    nationality: 'سعودية',
    tags: 'صيانة',
    notes: 'مقاول معتمد للصيانة الخفيفة والتكييف.',
    createdAt: '2026-01-20T07:45:00.000Z',
    updatedAt: '2026-01-20T07:45:00.000Z',
  },
];

export const SEED_PROPERTIES = [
  {
    id: 'property-001',
    name: 'عمارة النرجس السكنية',
    type: 'building',
    status: 'rented',
    deedNumber: '2457819034',
    nationalAddress: '6942 عثمان بن عفان، النرجس، الرياض 13336',
    city: 'الرياض',
    district: 'النرجس',
    address: 'طريق عثمان بن عفان',
    unitsCount: 6,
    areaSqm: 960,
    bedrooms: '',
    bathrooms: '',
    yearBuilt: '2021',
    floors: '3',
    ownerId: 'contact-owner-001',
    ownerName: 'خالد بن سعد العتيبي',
    ownerPhone: '0551203344',
    tenantContactId: 'contact-tenant-001',
    tenantName: 'عبدالله محمد الشهري',
    tenantPhone: '0558899100',
    maintenanceContactId: '',
    maintenanceContactName: '',
    maintenanceContactPhone: '',
    buyerContactId: '',
    buyerName: '',
    buyerPhone: '',
    purchasePrice: 3850000,
    monthlyRent: 14800,
    notes: 'أصل تشغيلي رئيسي للمكتب ويحتوي وحدات سكنية وتجارية.',
    createdAt: '2026-01-02T08:00:00.000Z',
    updatedAt: '2026-01-22T08:00:00.000Z',
  },
  {
    id: 'property-002',
    name: 'فيلا الياسمين',
    type: 'villa',
    status: 'available',
    deedNumber: '2457819035',
    nationalAddress: '3118 أنس بن مالك، الياسمين، الرياض 13325',
    city: 'الرياض',
    district: 'الياسمين',
    address: 'طريق أنس بن مالك',
    unitsCount: 1,
    areaSqm: 420,
    bedrooms: '5',
    bathrooms: '6',
    yearBuilt: '2023',
    floors: '2',
    ownerId: 'contact-owner-002',
    ownerName: 'نورة عبدالله القحطاني',
    ownerPhone: '0556647788',
    tenantContactId: '',
    tenantName: '',
    tenantPhone: '',
    maintenanceContactId: '',
    maintenanceContactName: '',
    maintenanceContactPhone: '',
    buyerContactId: '',
    buyerName: '',
    buyerPhone: '',
    purchasePrice: 2700000,
    monthlyRent: 14000,
    notes: 'جاهزة للعرض السكني الفاخر.',
    createdAt: '2026-01-06T09:10:00.000Z',
    updatedAt: '2026-01-06T09:10:00.000Z',
  },
  {
    id: 'property-003',
    name: 'مكتب التحلية الإداري',
    type: 'office',
    status: 'maintenance',
    deedNumber: '2457819036',
    nationalAddress: '7781 شارع التحلية، العليا، الرياض 12214',
    city: 'الرياض',
    district: 'العليا',
    address: 'شارع التحلية',
    unitsCount: 1,
    areaSqm: 180,
    bedrooms: '',
    bathrooms: '2',
    yearBuilt: '2019',
    floors: '1',
    ownerId: 'contact-owner-001',
    ownerName: 'خالد بن سعد العتيبي',
    ownerPhone: '0551203344',
    tenantContactId: '',
    tenantName: '',
    tenantPhone: '',
    maintenanceContactId: 'contact-supplier-001',
    maintenanceContactName: 'مؤسسة روافد الصيانة',
    maintenanceContactPhone: '0559922114',
    buyerContactId: '',
    buyerName: '',
    buyerPhone: '',
    purchasePrice: 930000,
    monthlyRent: 9500,
    notes: 'قيد معالجة أعمال تكييف وتشطيبات داخلية.',
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-01-24T10:00:00.000Z',
  },
  {
    id: 'property-004',
    name: 'أرض القيروان الاستثمارية',
    type: 'land',
    status: 'sold',
    deedNumber: '2457819037',
    nationalAddress: '6231 طريق الأمير محمد بن سعد، القيروان، الرياض 13532',
    city: 'الرياض',
    district: 'القيروان',
    address: 'طريق الأمير محمد بن سعد',
    unitsCount: 1,
    areaSqm: 875,
    bedrooms: '',
    bathrooms: '',
    yearBuilt: '',
    floors: '',
    ownerId: 'contact-owner-002',
    ownerName: 'نورة عبدالله القحطاني',
    ownerPhone: '0556647788',
    tenantContactId: '',
    tenantName: '',
    tenantPhone: '',
    maintenanceContactId: '',
    maintenanceContactName: '',
    maintenanceContactPhone: '',
    buyerContactId: 'contact-buyer-001',
    buyerName: 'شركة أفق التطوير العقارية',
    buyerPhone: '0114027766',
    purchasePrice: 1650000,
    monthlyRent: '',
    notes: 'تم إتمام البيع وتوثيق الصفقة استثماريًا.',
    createdAt: '2026-01-11T13:30:00.000Z',
    updatedAt: '2026-02-01T13:30:00.000Z',
  },
];

export const SEED_UNITS = [
  {
    id: 'unit-001',
    propertyId: 'property-001',
    name: 'شقة 101',
    type: 'apartment',
    floor: '1',
    areaSqm: 125,
    rooms: 3,
    bathrooms: 2,
    monthlyRent: 3200,
    status: 'occupied',
    notes: 'واجهة شمالية.',
    createdAt: '2026-01-02T08:30:00.000Z',
    updatedAt: '2026-01-02T08:30:00.000Z',
  },
  {
    id: 'unit-002',
    propertyId: 'property-001',
    name: 'شقة 102',
    type: 'apartment',
    floor: '1',
    areaSqm: 120,
    rooms: 3,
    bathrooms: 2,
    monthlyRent: 3100,
    status: 'occupied',
    notes: '',
    createdAt: '2026-01-02T08:31:00.000Z',
    updatedAt: '2026-01-02T08:31:00.000Z',
  },
  {
    id: 'unit-003',
    propertyId: 'property-001',
    name: 'شقة 201',
    type: 'apartment',
    floor: '2',
    areaSqm: 130,
    rooms: 4,
    bathrooms: 3,
    monthlyRent: 3400,
    status: 'vacant',
    notes: 'جاهزة للتسويق.',
    createdAt: '2026-01-02T08:32:00.000Z',
    updatedAt: '2026-01-02T08:32:00.000Z',
  },
  {
    id: 'unit-004',
    propertyId: 'property-001',
    name: 'شقة 202',
    type: 'apartment',
    floor: '2',
    areaSqm: 130,
    rooms: 4,
    bathrooms: 3,
    monthlyRent: 3400,
    status: 'occupied',
    notes: '',
    createdAt: '2026-01-02T08:33:00.000Z',
    updatedAt: '2026-01-02T08:33:00.000Z',
  },
  {
    id: 'unit-005',
    propertyId: 'property-001',
    name: 'شقة 301',
    type: 'apartment',
    floor: '3',
    areaSqm: 135,
    rooms: 4,
    bathrooms: 3,
    monthlyRent: 3600,
    status: 'maintenance',
    notes: 'تغيير سباكة ومكيفات.',
    createdAt: '2026-01-02T08:34:00.000Z',
    updatedAt: '2026-01-22T08:34:00.000Z',
  },
  {
    id: 'unit-006',
    propertyId: 'property-001',
    name: 'محل A',
    type: 'shop',
    floor: 'أرضي',
    areaSqm: 85,
    rooms: 1,
    bathrooms: 1,
    monthlyRent: 5500,
    status: 'occupied',
    notes: 'نشاط تقني وخدمات مكتبية.',
    createdAt: '2026-01-02T08:35:00.000Z',
    updatedAt: '2026-01-02T08:35:00.000Z',
  },
];

export const SEED_CONTRACTS = [
  {
    id: 'contract-001',
    propertyId: 'property-001',
    unitId: 'unit-001',
    contactId: 'contact-tenant-001',
    contractNumber: 'RE-2026-001',
    type: 'rent',
    status: 'active',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    durationMonths: 12,
    totalAmount: 38400,
    monthlyRent: 3200,
    depositAmount: 3200,
    paymentCycle: 'monthly',
    installmentCount: 12,
    autoRenew: true,
    notes: 'سداد في بداية كل شهر.',
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'contract-002',
    propertyId: 'property-001',
    unitId: 'unit-002',
    contactId: 'contact-tenant-002',
    contractNumber: 'RE-2026-002',
    type: 'rent',
    status: 'active',
    startDate: '2026-02-01',
    endDate: '2027-01-31',
    durationMonths: 12,
    totalAmount: 37200,
    monthlyRent: 3100,
    depositAmount: 3100,
    paymentCycle: 'monthly',
    installmentCount: 12,
    autoRenew: false,
    notes: '',
    createdAt: '2026-02-01T09:00:00.000Z',
    updatedAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'contract-003',
    propertyId: 'property-001',
    unitId: 'unit-006',
    contactId: 'contact-tenant-003',
    contractNumber: 'RE-2025-091',
    type: 'rent',
    status: 'expired',
    startDate: '2025-03-01',
    endDate: '2026-02-28',
    durationMonths: 12,
    totalAmount: 66000,
    monthlyRent: 5500,
    depositAmount: 5500,
    paymentCycle: 'quarterly',
    installmentCount: 4,
    autoRenew: false,
    notes: 'بانتظار قرار التجديد التجاري.',
    createdAt: '2025-03-01T10:00:00.000Z',
    updatedAt: '2026-02-28T10:00:00.000Z',
  },
  {
    id: 'contract-004',
    propertyId: 'property-004',
    unitId: '',
    contactId: 'contact-buyer-001',
    contractNumber: 'SA-2026-004',
    type: 'sale',
    status: 'active',
    startDate: '2026-02-10',
    endDate: '2026-04-10',
    durationMonths: 2,
    totalAmount: 1850000,
    monthlyRent: '',
    depositAmount: 150000,
    paymentCycle: 'custom',
    installmentCount: 2,
    autoRenew: false,
    notes: 'صفقة بيع أرض استثمارية مع دفعتين.',
    createdAt: '2026-02-10T11:30:00.000Z',
    updatedAt: '2026-02-10T11:30:00.000Z',
  },
];

export const SEED_CONTRACT_PAYMENTS = [
  {
    id: 'contract-payment-001',
    contractId: 'contract-001',
    amount: 3200,
    date: '2026-01-01',
    paymentMethod: 'bank_transfer',
    note: 'سداد دفعة يناير',
    dueId: 'contract-001-due-1',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-01-01T09:00:00.000Z',
  },
  {
    id: 'contract-payment-002',
    contractId: 'contract-001',
    amount: 3200,
    date: '2026-02-01',
    paymentMethod: 'bank_transfer',
    note: 'سداد دفعة فبراير',
    dueId: 'contract-001-due-2',
    createdAt: '2026-02-01T09:00:00.000Z',
    updatedAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'contract-payment-003',
    contractId: 'contract-002',
    amount: 3100,
    date: '2026-02-01',
    paymentMethod: 'electronic',
    note: 'الدفعة الأولى',
    dueId: 'contract-002-due-1',
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'contract-payment-004',
    contractId: 'contract-003',
    amount: 16500,
    date: '2025-03-01',
    paymentMethod: 'bank_transfer',
    note: 'الدفعة الربعية الأولى',
    dueId: 'contract-003-due-1',
    createdAt: '2025-03-01T12:00:00.000Z',
    updatedAt: '2025-03-01T12:00:00.000Z',
  },
  {
    id: 'contract-payment-005',
    contractId: 'contract-003',
    amount: 16500,
    date: '2025-06-01',
    paymentMethod: 'bank_transfer',
    note: 'الدفعة الربعية الثانية',
    dueId: 'contract-003-due-2',
    createdAt: '2025-06-01T12:00:00.000Z',
    updatedAt: '2025-06-01T12:00:00.000Z',
  },
  {
    id: 'contract-payment-006',
    contractId: 'contract-004',
    amount: 925000,
    date: '2026-02-10',
    paymentMethod: 'bank_transfer',
    note: 'الدفعة الأولى من صفقة البيع',
    dueId: 'contract-004-due-1',
    createdAt: '2026-02-10T13:00:00.000Z',
    updatedAt: '2026-02-10T13:00:00.000Z',
  },
];

// ============================================
// سندات القبض — SEED_CONTRACT_RECEIPTS
// ============================================
export const SEED_CONTRACT_RECEIPTS = [
  {
    id: 'receipt-001',
    contractPaymentId: 'contract-payment-001',
    contractId: 'contract-001',
    receiptNumber: 'RCP-20260101-A1B2',
    issueDate: '2026-01-01',
    tenantName: 'أحمد محمد العتيبي',
    contractNumber: 'CNT-2026-001',
    propertyName: 'برج النخيل السكني',
    unitName: 'شقة 301',
    amount: 3200,
    paymentMethod: 'bank_transfer',
    paymentMethodLabel: 'تحويل بنكي',
    dueId: 'contract-001-due-1',
    installmentNumber: '1',
    note: 'سداد دفعة يناير',
    officeName: 'قيد العقار',
    createdAt: '2026-01-01T09:00:00.000Z',
    updatedAt: '2026-01-01T09:00:00.000Z',
  },
  {
    id: 'receipt-002',
    contractPaymentId: 'contract-payment-002',
    contractId: 'contract-001',
    receiptNumber: 'RCP-20260201-C3D4',
    issueDate: '2026-02-01',
    tenantName: 'أحمد محمد العتيبي',
    contractNumber: 'CNT-2026-001',
    propertyName: 'برج النخيل السكني',
    unitName: 'شقة 301',
    amount: 3200,
    paymentMethod: 'bank_transfer',
    paymentMethodLabel: 'تحويل بنكي',
    dueId: 'contract-001-due-2',
    installmentNumber: '2',
    note: 'سداد دفعة فبراير',
    officeName: 'قيد العقار',
    createdAt: '2026-02-01T09:00:00.000Z',
    updatedAt: '2026-02-01T09:00:00.000Z',
  },
];

// ============================================
// نسخة احتياطية ورسائل تخزين
// ============================================
export const BACKUP_VERSION = 1;
export const STORAGE_ERROR_MESSAGE =
  'لم يتم الحفظ. مساحة التخزين ممتلئة. يُنصح بتصدير نسخة احتياطية ثم حذف بعض البيانات.';

// ============================================
// إعادة تصدير مجمّعة (default)
// ============================================
export default {
  KEYS,
  MSG,
  TRANSACTION_TYPES,
  TRANSACTION_CATEGORIES,
  PAYMENT_METHODS,
  COMMISSION_STATUSES,
  LETTER_TYPES,
  DASHBOARD_PERIOD_OPTIONS,
  NAV_ITEMS,
  SEED_TRANSACTIONS,
  SEED_COMMISSIONS,
  SEED_DRAFTS,
  SEED_SETTINGS,
  SEED_PROPERTIES,
  SEED_UNITS,
  SEED_CONTACTS,
  SEED_CONTRACTS,
  SEED_CONTRACT_PAYMENTS,
  SEED_CONTRACT_RECEIPTS,
  BACKUP_VERSION,
  STORAGE_ERROR_MESSAGE,
};
